language: node_js
node_js:
  - lts/*
  - node

script:
  - npm run lint
  - npm run build

deploy:
  - provider: npm
    edge: true
    run_script: publish
    on:
      tags: true
      node_js: lts/*
